### ISSUE TITLE
Default Cert

### ISSUE THREAD

**Issue by Crypt0Graphic** [now-ims/fastify-firebase#5]
Where should we put default cert? What should be it's extension and content? Can't see in docs.

**Comment by Crypt0Graphic** [comment]
Ok i found. We need a Private Key from Firebase. Then copy that Json to somewhere.

**Comment by puchesjr** [comment]
The default certificate can be retrieved from your Google Cloud console or Firebase Console. However, if you're hosting on Google Cloud you typically will not need to download the Service Account certificate.

Where and how you decide to store your SA Certificate, should you need one, is entirely up to you. You could serve from a Google Cloud Storage, Google Cloud Secrets Manager, Google Cloud KMS, etc.  If we use a cert we typically use Google Cloud Secrets Manager.
