### ISSUE TITLE
Problem connection

### ISSUE THREAD

**Issue by DDT88** [now-ims/fastify-firebase#7]
Hi,  

i need help me. 
I recived this error in run app.

"Failed to parse service account json file: Error: Failed to parse private key: Error: Invalid PEM formatted message."

How i generate pem file ? 
Thanks.

**Comment by puchesjr** [comment]
Would you mind providing a code snippet of your fastify-firebase plugin configuration?  Please be sure to omit any secret information.  To understand how to create the service account and to generate the private key see link - https://firebase.google.com/docs/admin/setup#initialize-sdk
